language: node_js
node_js:
  - node
  - iojs
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/351ddadf95364792d533
    on_success: change  
    on_failure: change
    on_start: never 
